import { relations } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  text,
  varchar,
  integer,
  smallint,
  real,
  boolean,
  timestamp,
  jsonb,
  bigserial,
  uuid,
  primaryKey,
  index,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// better-auth tables (schema shape matches better-auth's Drizzle adapter
// conventions: text ids generated by better-auth's own id generator, not
// serial/uuid columns). Kept here rather than auto-generated so app tables
// and auth tables share one migration pipeline.
// ---------------------------------------------------------------------------

export const planEnum = pgEnum("plan", ["free", "premium"]);

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  plan: planEnum("plan").notNull().default("free"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  token: text("token").notNull().unique(),
  expiresAt: timestamp("expires_at").notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// App tables
// ---------------------------------------------------------------------------

export const practiceCategoryEnum = pgEnum("practice_category", [
  "code",
  "prose",
  "quote",
]);

export const practiceSourceEnum = pgEnum("practice_source", [
  "curated",
  "user_import",
]);

export const keystrokeEventTypeEnum = pgEnum("keystroke_event_type", [
  "char",
  "backspace",
  "correction",
]);

export const practiceTexts = pgTable("practice_texts", {
  id: uuid("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  title: text("title").notNull(),
  body: text("body").notNull(),
  category: practiceCategoryEnum("category").notNull(),
  languageLayout: varchar("language_layout", { length: 32 })
    .notNull()
    .default("en-us-qwerty"),
  difficulty: smallint("difficulty").notNull().default(1),
  charCount: integer("char_count").notNull(),
  // Phase 1 only ever inserts 'curated'; 'user_import' + ownerUserId are
  // unused until Phase 2 (train-on-your-own-code) but cheap to add now and
  // awkward to migrate in once rows already exist.
  source: practiceSourceEnum("source").notNull().default("curated"),
  ownerUserId: text("owner_user_id").references(() => user.id, {
    onDelete: "cascade",
  }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const typingAttempts = pgTable("typing_attempts", {
  id: uuid("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  practiceTextId: uuid("practice_text_id")
    .notNull()
    .references(() => practiceTexts.id, { onDelete: "cascade" }),
  startedAt: timestamp("started_at").notNull(),
  completedAt: timestamp("completed_at").notNull(),
  durationMs: integer("duration_ms").notNull(),
  wpm: real("wpm").notNull(),
  rawWpm: real("raw_wpm").notNull(),
  accuracyPct: real("accuracy_pct").notNull(),
  totalChars: integer("total_chars").notNull(),
  correctChars: integer("correct_chars").notNull(),
  errorCount: integer("error_count").notNull(),
  uncorrectedErrorCount: integer("uncorrected_error_count").notNull(),
  clientMeta: jsonb("client_meta"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const keystrokeEvents = pgTable(
  "keystroke_events",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    attemptId: uuid("attempt_id")
      .notNull()
      .references(() => typingAttempts.id, { onDelete: "cascade" }),
    seq: integer("seq").notNull(),
    // Milliseconds relative to attempt start (never wall-clock) so client
    // clock skew can't leak into WPM math.
    timestampMs: integer("timestamp_ms").notNull(),
    // Layout-dependent character produced.
    key: varchar("key", { length: 16 }).notNull(),
    // KeyboardEvent.code — physical key, layout-independent. Kept alongside
    // `key` from day one: this is the join target for a future finger/hand
    // mapping table, and retrofitting it later would lose all keystroke
    // history collected before the change.
    code: varchar("code", { length: 32 }).notNull(),
    expectedChar: varchar("expected_char", { length: 8 }),
    isCorrect: boolean("is_correct").notNull(),
    eventType: keystrokeEventTypeEnum("event_type").notNull(),
    interKeyIntervalMs: integer("inter_key_interval_ms"),
  },
  (table) => [index("keystroke_events_attempt_id_idx").on(table.attemptId)],
);

export const keyStats = pgTable(
  "key_stats",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    key: varchar("key", { length: 16 }).notNull(),
    attemptsCount: integer("attempts_count").notNull().default(0),
    correctCount: integer("correct_count").notNull().default(0),
    incorrectCount: integer("incorrect_count").notNull().default(0),
    avgLatencyMs: real("avg_latency_ms"),
    lastPracticedAt: timestamp("last_practiced_at"),
  },
  (table) => [primaryKey({ columns: [table.userId, table.key] })],
);

export const typingAttemptsRelations = relations(typingAttempts, ({ one }) => ({
  practiceText: one(practiceTexts, {
    fields: [typingAttempts.practiceTextId],
    references: [practiceTexts.id],
  }),
}));
